name: "Gradle Cache"

description: "Ensures the gradle cache is being used to speed up builds."

runs:
  using: "composite"
  steps:
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('build.gradle') }}